apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx:1
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        command: ["/bin/sleep", "3650d"]
        image: nginx
        ports:
        - containerPort: 80
