apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: open-cluster-management-observability
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_match:
          severity: critical
        target_match_re:
          severity: warning|info
      - equal:
          - namespace
          - alertname
        source_match:
          severity: warning
        target_match_re:
          severity: info
    receivers:
      - name: Critical
      - name: Default
        slack_configs:
          - channel: alertmanager-tester
            api_url: >-
              https://hooks.slack.com/services/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
      - name: Watchdog
        slack_configs:
          - channel: alertmanager-tester
            api_url: >-
              https://hooks.slack.com/services/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
    route:
      group_by:
        - namespace
      group_interval: 5m
      group_wait: 30s
      receiver: Default
      repeat_interval: 6m
      routes:
        - receiver: Watchdog
          match:
            alertname: Watchdog
        - match:
            severity: critical
          receiver: Critical
