kind: ConfigMap
apiVersion: v1
metadata:
  name: thanos-ruler-custom-rules
  namespace: open-cluster-management
data:
  custom_rules.yaml: |
    groups:
    - name: WatchDog
      rules: 
        - alert: Watchdog
          expr: vector(1)
          labels:
            severity: none
          annotations:
            message: |
              MCO alert-manager tester. Always fire.
