apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-03-28T01:49:21Z"
  generation: 6
  labels:
    olm.deployment-spec-hash: 99d864cf9
    olm.owner: advanced-cluster-management.v2.3.0
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: open-cluster-management
    operators.coreos.com/advanced-cluster-management.open-cluster-management: ""
  name: multicluster-observability-operator-debug
  namespace: open-cluster-management
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: multicluster-observability-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: multicluster-observability-operator
    spec:
      containers:
      - args:
        - -leader-elect
        command:
        - mco-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: COMPONENT_VERSION
          value: 2.3.0
        - name: OPERATOR_NAME
          value: multicluster-observability-operator
        - name: TEMPLATES_PATH
          value: /usr/local/manifests
        - name: SPOKE_NAMESPACE
          value: open-cluster-management-addon-observability
        - name: OPERATOR_CONDITION_NAME
          value: advanced-cluster-management.v2.3.0
        image: clyang/multicluster-observability-operator:latest 
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: multicluster-observability-operator
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: multicluster-observability-operator
      serviceAccountName: multicluster-observability-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
status:
  conditions:
  - lastTransitionTime: "2021-03-28T01:49:21Z"
    lastUpdateTime: "2021-03-28T01:49:40Z"
    message: ReplicaSet "multicluster-observability-operator-65c6dfd6f5" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-29T01:59:09Z"
    lastUpdateTime: "2021-03-29T01:59:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
