apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-observability-operator-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-observability-operator-debug
  template:
    metadata:
      labels:
        name: multicluster-observability-operator-debug
    spec:
      serviceAccountName: multicluster-observability-operator
      containers:
        - name: multicluster-observability-operator
          # Replace this with the built image name
          image: clyang/multicluster-observability-operator:v0.1.0 
          command:
          - mco-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "multicluster-observability-operator"
            - name: TEMPLATES_PATH
              value: /usr/local/manifests
            - name: SPOKE_NAMESPACE
              value: open-cluster-management-addon-observability
