name: go

on:
  push:
    branches:
      - main
    tags:
  pull_request:

# TODO(bwplotka): Add tests here.
jobs:
  e2e:
    runs-on: ubuntu-latest
    name: tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x

      - name: Check out code into the Go module directory.
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run e2e docker-based tests.
        run: docker version
