apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDZzCCAk+gAwIBAgIQHsbwMRedZaLll2n9vphh0TANBgkqhkiG9w0BAQsFADBF
    MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxLDAqBgNVBAMTI29ic2VydmFiaWxpdHkt
    c2VydmVyLWNhLWNlcnRpZmljYXRlMB4XDTIwMDkwMzA5MDU1M1oXDTIwMTIwMjA5
    MDU1M1owRTEVMBMGA1UEChMMY2VydC1tYW5hZ2VyMSwwKgYDVQQDEyNvYnNlcnZh
    YmlsaXR5LXNlcnZlci1jYS1jZXJ0aWZpY2F0ZTCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAMRjxm/6+cgT2l3CW+3Vb+sqG7+kER3H145wfPkDOsE6wV0Y
    nqKo1kNRNVq4DuqMfSt5KkqXFTyJHSlWPfDCRdp0TwPyllyhVdI5CBoTvkkTxm2D
    /E65yIfdIldxIdziqjXH8rHeBWjY+2oibRdb0opyzutXsOdKsOhP1SF+dhonwGUz
    Sfyz9hzPLVf2cKVgf/MA76J4Eh2zCSZr95lJNIFyAyAUOxwBa+1XZX4KpjglCa8c
    77eRXSZc8j5fM38nRfHUSa0zBx2Yo23fIznNILmG8bLe1bt70DR4VQ5/c2l5zBeI
    VFrf6bYrmrxwb90xOxeHJ1mtqmFiOGqA7ynmw9kCAwEAAaNTMFEwDgYDVR0PAQH/
    BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wLgYDVR0RBCcwJYIjb2JzZXJ2YWJpbGl0
    eS1zZXJ2ZXItY2EtY2VydGlmaWNhdGUwDQYJKoZIhvcNAQELBQADggEBAHfxQBk6
    bzOHrO0PtXIjvq+PKDDQJ5EPn6dC1NGIQxbLHKSLR8YHhYI6jBBitfS9KICt2oQM
    yoNKidDRua0Yh3e2x72HOxD2bAU6ZhfsHiM6E9UCfua6APTgISExKYRZ/pqvbuHw
    JxDWk18mfGjjVdDRbNZ2FVideiq3m8nBt31t55awdslZSKwdSJlEd2ofwYlqC94a
    HzAdCPBReqVd6IwOKeTK1Gx5Il0ItkxV77xgM0DpUwTnfs6wEaNBFDM8UpJzDIHx
    2v8UT5E4MZ1Lxbvg0qGAZy42uiRyQm/ssBXyXeD5Q/GxmkL9oMTznORcU2q/gCF5
    8m1M/V5/d4/100g=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: observability-server-ca-certs
