apiVersion: batch/v1
kind: Job
metadata:
  name: observatorium-up-metrics
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/component: test
        app.kubernetes.io/instance: e2e-test
        app.kubernetes.io/name: observatorium-up
        app.kubernetes.io/version: master-2020-06-15-d763595
    spec:
      containers:
      - args:
        - --endpoint-type=metrics
        - --endpoint-write=http://observability-observatorium-thanos-receive:19291/api/v1/receive
        - --endpoint-read=https://observatorium-api-open-cluster-management-observability.apps.cyang-ocp2.dev05.red-chesterfield.com/api/metrics/v1/default/api/v1/query
        - --tls-ca-file=/var/run/secrets/tls/ca.crt
        - --tls-client-cert-file=/var/run/secrets/tls/tls.crt
        - --tls-client-private-key-file=/var/run/secrets/tls/tls.key
        - --period=1s
        - --duration=2m
        - --name=foo
        - --labels=bar="baz"
        - --latency=10s
        - --initial-query-delay=5s
        - --threshold=0.90
        image: quay.io/observatorium/up:master-2020-06-15-d763595
        name: observatorium-up
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/shared
          name: shared
          readOnly: false
        - mountPath: /var/run/secrets/tls
          name: certs
      restartPolicy: OnFailure
      volumes:
      - emptyDir: {}
        name: shared
      - name: certs
        secret:
          secretName: observability-server-certs
